#logging.file.name=logs/app.log
#logging.pattern.file=%d %p %c{1.} {%t} %m%n


---
spring:
  jpa:
    hibernate:
      ddl-auto: create
      properties:
        hibernate:
          dialect: org.hibernate.dialect.MySQL5Dialect



  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: ${CLEARDB_DATABASE_URL}
    username: ${USERNAME}
    password: ${PASSWORD}
    initialization-mode:  always
    platform: mysql

  server:
    port: ${PORT}
    error:
      path: /error
      whitelable:
        enable: false



  recipe:
    book:
      page-size: 20






